In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Users/moham/Downloads/Student_Performance_Dataset (1).csv")

In [3]:
df.head()

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail

In [4]:
df.shape

(5000, 16)

In [5]:
df.nunique()

Student_ID                    5000
Age                              6
Gender                           2
Class                            4
Study_Hours_Per_Day             56
Attendance_Percentage           51
Parental_Education               3
Internet_Access                  2
Extracurricular_Activities       2
Math_Score                      66
Science_Score                   66
English_Score                   66
Previous_Year_Score             56
Final_Percentage               181
Performance_Level                4
Pass_Fail                        2
dtype: int64

In [6]:
df.isnull().sum()

Student_ID                    0
Age                           0
Gender                        0
Class                         0
Study_Hours_Per_Day           0
Attendance_Percentage         0
Parental_Education            0
Internet_Access               0
Extracurricular_Activities    0
Math_Score                    0
Science_Score                 0
English_Score                 0
Previous_Year_Score           0
Final_Percentage              0
Performance_Level             0
Pass_Fail                     0
dtype: int64

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ---------- 1. Scan all numeric columns ----------
def iqr_outliers(s):
    q1, q3 = s.quantile([.25, .75])
    iqr = q3 - q1
    return (s < q1 - 1.5*iqr) | (s > q3 + 1.5*iqr)

num_cols = df.select_dtypes(include='number').columns

summary = pd.DataFrame({
    'outliers': df[num_cols].apply(iqr_outliers).sum(),
    'percent': (df[num_cols].apply(iqr_outliers).mean() * 100).round(2),
    'skew': df[num_cols].skew().round(2)
}).sort_values('outliers', ascending=False)
print(summary)

                       outliers  percent  skew
Age                           0      0.0 -0.02
Class                         0      0.0  0.01
Study_Hours_Per_Day           0      0.0 -0.02
Attendance_Percentage         0      0.0  0.00
Math_Score                    0      0.0 -0.03
Science_Score                 0      0.0  0.04
English_Score                 0      0.0 -0.02
Previous_Year_Score           0      0.0  0.01
Final_Percentage              0      0.0 -0.02

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  5000 non-null   str
 1   Age                         5000 non-null   int64
 2   Gender                      5000 non-null   str
 3   Class                       5000 non-null   int64
 4   Study_Hours_Per_Day         5000 non-null   float64
 5   Attendance_Percentage       5000 non-null   int64
 6   Parental_Education          5000 non-null   str
 7   Internet_Access             5000 non-null   str
 8   Extracurricular_Activities  5000 non-null   str
 9   Math_Score                  5000 non-null   int64
 10  Science_Score               5000 non-null   int64
 11  English_Score               5000 non-null   int64
 12  Previous_Year_Score         5000 non-null   int64
 13  Final_Percentage            5000 non-null   float64
 14  Performance_Level           5000 non-null   str
 15  Pass_Fail                   5000 non-null   str
dtypes: float64(2), int64(7), str(7)
memory usage: 796.5 KB

In [9]:
import pandas as pd
from scipy.stats import chi2_contingency
target = 'Pass_Fail'
# Select categorical columns
categorical_columns = df.select_dtypes(
    include=['object', 'category', 'bool']
).columns
# Remove the target column
categorical_columns = categorical_columns.drop(
    target, errors='ignore'
)
chi_results = []
for col in categorical_columns:
    # Create a contingency table
    contingency_table = pd.crosstab(df[col], df[target])
    # Perform Chi-Square test
    chi2, p_value, dof, expected = chi2_contingency(
        contingency_table
    )
    chi_results.append({
        'Feature': col,
        'Chi2_Statistic': chi2,
        'P_Value': p_value,
        'Relationship': 'Significant'
        if p_value < 0.05 else 'Not Significant'
    })
# Display results
chi_df = pd.DataFrame(chi_results)
display(chi_df.sort_values(by='P_Value'))

C:\Users\moham\AppData\Local\Temp\ipykernel_7144\684301653.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

                      Feature  Chi2_Statistic   P_Value     Relationship
5           Performance_Level     5000.000000  0.000000      Significant
0                  Student_ID     5000.000000  0.493351  Not Significant
4  Extracurricular_Activities        0.399617  0.527287  Not Significant
2          Parental_Education        0.645978  0.723982  Not Significant
3             Internet_Access        0.034337  0.852991  Not Significant
1                      Gender        0.010437  0.918630  Not Significant

In [10]:
# Identify insignificant categorical features
insignificant_cols = chi_df.loc[
    chi_df['P_Value'] >= 0.05, 'Feature'
].tolist()
# Drop insignificant columns
df = df.drop(columns=insignificant_cols)
print("Dropped columns:", insignificant_cols)
print("Remaining columns:", df.columns.tolist())

Dropped columns: ['Student_ID', 'Gender', 'Parental_Education', 'Internet_Access', 'Extracurricular_Activities']
Remaining columns: ['Age', 'Class', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Math_Score', 'Science_Score', 'English_Score', 'Previous_Year_Score', 'Final_Percentage', 'Performance_Level', 'Pass_Fail']

In [11]:
import pandas as pd
from scipy.stats import f_oneway
target = 'Pass_Fail'
# Select numerical columns
numerical_columns = df.select_dtypes(
    include='number'
).columns.drop(target, errors='ignore')
anova_results = []
for col in numerical_columns:
    # Select feature values for each class
    group_0 = df.loc[
        df[target].astype(str).str.strip().str.lower() == 'pass',
        col
    ].dropna()
    group_1 = df.loc[
        df[target].astype(str).str.strip().str.lower() == 'fail',
        col
    ].dropna()
    # Check whether both groups contain enough values
    if len(group_0) < 2 or len(group_1) < 2:
        continue
    # Perform ANOVA
    f_stat, p_value = f_oneway(group_0, group_1)
    anova_results.append({
        'Feature': col,
        'F_Statistic': f_stat,
        'P_Value': p_value,
        'Relationship': (
            'Significant' if p_value < 0.05
            else 'Not Significant'
        )
    })

anova_df = pd.DataFrame(anova_results)
print(anova_df.sort_values('P_Value'))

                 Feature  F_Statistic        P_Value     Relationship
8       Final_Percentage  1420.482910  7.906894e-274      Significant
6          English_Score   420.124544   1.023178e-89      Significant
4             Math_Score   402.575398   3.462851e-86      Significant
5          Science_Score   366.289900   7.497760e-79      Significant
7    Previous_Year_Score     2.939837   8.648144e-02  Not Significant
2    Study_Hours_Per_Day     0.819706   3.653099e-01  Not Significant
3  Attendance_Percentage     0.581390   4.458041e-01  Not Significant
1                  Class     0.180703   6.707885e-01  Not Significant
0                    Age     0.139454   7.088399e-01  Not Significant

In [12]:
# Identify insignificant numerical features
insignificant_cols = anova_df.loc[
    anova_df['P_Value'] >= 0.05, 'Feature'
].tolist()
# Drop insignificant columns from the dataset
df = df.drop(columns=insignificant_cols)
print("Dropped columns:", insignificant_cols)
print("Remaining columns:", df.columns.tolist())

Dropped columns: ['Age', 'Class', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Previous_Year_Score']
Remaining columns: ['Math_Score', 'Science_Score', 'English_Score', 'Final_Percentage', 'Performance_Level', 'Pass_Fail']

In [13]:
df.head()

,Math_Score,Science_Score,English_Score,Final_Percentage,Performance_Level,Pass_Fail
0,40,39,72,50.33,Average,Pass
1,80,44,35,53.00,Average,Pass
2,83,73,59,71.67,Good,Pass
3,68,48,77,64.33,Average,Pass
4,41,46,36,41.00,Poor,Fail

In [14]:
from sklearn.preprocessing import LabelEncoder
Label = LabelEncoder()
df["Performance_Level"]=Label.fit_transform(df["Performance_Level"])
df["Pass_Fail"]=Label.fit_transform(df["Pass_Fail"])

In [15]:
df.head()

,Math_Score,Science_Score,English_Score,Final_Percentage,Performance_Level,Pass_Fail
0,40,39,72,50.33,0,1
1,80,44,35,53.00,0,1
2,83,73,59,71.67,2,1
3,68,48,77,64.33,0,1
4,41,46,36,41.00,3,0

In [16]:
x=df.iloc[:,0:5]
x

,Math_Score,Science_Score,English_Score,Final_Percentage,Performance_Level
0,40,39,72,50.33,0
1,80,44,35,53.00,0
2,83,73,59,71.67,2
3,68,48,77,64.33,0
4,41,46,36,41.00,3
...,...,...,...,...,...
4995,64,60,70,64.67,0
4996,44,59,43,48.67,3
4997,95,41,82,72.67,2
4998,66,45,61,57.33,0
4999,69,53,87,69.67,2

In [17]:
y=df.iloc[:,5]
y

0       1
1       1
2       1
3       1
4       0
       ..
4995    1
4996    0
4997    1
4998    1
4999    1
Name: Pass_Fail, Length: 5000, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
x_train

,Math_Score,Science_Score,English_Score,Final_Percentage,Performance_Level
4227,47,95,95,79.00,2
4676,75,84,94,84.33,1
800,91,60,72,74.33,2
3671,41,67,91,66.33,2
4193,35,40,93,56.00,0
...,...,...,...,...,...
4426,50,94,44,62.67,0
466,92,80,88,86.67,1
3092,77,93,44,71.33,2
3772,54,78,55,62.33,0
860,100,93,94,95.67,1

In [20]:
x_test

,Math_Score,Science_Score,English_Score,Final_Percentage,Performance_Level
1501,76,48,54,59.33,0
2586,36,63,91,63.33,0
2653,43,78,62,61.00,0
1055,94,63,50,69.00,2
705,79,51,88,72.67,2
...,...,...,...,...,...
4711,68,73,96,79.00,2
2313,54,77,91,74.00,2
3214,47,92,40,59.67,0
2732,56,72,69,65.67,0
1926,95,65,38,66.00,2

In [21]:
y_train.value_counts()

Pass_Fail
1    3795
0     205
Name: count, dtype: int64

In [22]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
x_sm, y_sm = smote.fit_resample(x_train, y_train)
y_sm.value_counts()

Pass_Fail
1    3795
0    3795
Name: count, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X = df.drop('Pass_Fail', axis=1)
y = df['Pass_Fail']
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
num_cols = X_train.select_dtypes(
    include=['int64', 'float64']
).columns
scaler = MinMaxScaler()
x_train[num_cols] = scaler.fit_transform(X_train[num_cols])
x_test[num_cols] = scaler.transform(X_test[num_cols])

In [24]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [25]:
#import the model
#training (x_train,y_train)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [26]:
model.fit(x_train_scaled,y_train)

LogisticRegression()

In [27]:
x_pred=model.predict(x_train_scaled)

In [28]:
from sklearn.metrics import accuracy_score
train_acc = accuracy_score(x_pred,y_train)
print("training accuracy is ",train_acc)

training accuracy is  1.0

In [29]:
y_pred=model.predict(x_test_scaled)

In [30]:
from sklearn.metrics import accuracy_score
test_acc = accuracy_score(y_test,y_pred)
print("testing accuracy is ",test_acc)

testing accuracy is  1.0

In [31]:
from sklearn.metrics import classification_report
# Display classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       940

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

In [32]:
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsClassifier()

In [33]:
model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [34]:
x_pred=model.predict(x_train_scaled)

In [35]:
from sklearn.metrics import accuracy_score
train_acc = accuracy_score(x_pred,y_train)
print("training accuracy is ",train_acc)

training accuracy is  1.0

In [36]:
y_pred=model.predict(x_test_scaled)

In [37]:
from sklearn.metrics import accuracy_score
test_acc = accuracy_score(y_test,y_pred)
print("testing accuracy is ",test_acc)

testing accuracy is  1.0

In [38]:
from sklearn.model_selection import GridSearchCV
KNN_PARAMETER = {'n_neighbors': [3, 5, 7, 11],'metric': ['euclidean', 'manhattan']}
grid_search = GridSearchCV(KNeighborsClassifier(), KNN_PARAMETER, cv=5)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 11]})

In [39]:
from sklearn.metrics import classification_report
# Display classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       940

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

In [40]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
model = SVC()

In [41]:
model.fit(x_train_scaled,y_train)

SVC()

In [42]:
x_pred=model.predict(x_train_scaled)

In [43]:
from sklearn.metrics import accuracy_score
train_acc = accuracy_score(x_pred,y_train)
print("training accuracy is ",train_acc)

training accuracy is  1.0

In [44]:
y_pred=model.predict(x_test_scaled)

In [45]:
from sklearn.metrics import accuracy_score
test_acc = accuracy_score(y_test,y_pred)
print("testing accuracy is ",test_acc)

testing accuracy is  1.0

In [46]:
from sklearn.metrics import classification_report
# Display classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       940

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

In [47]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion= 'gini', max_depth= None, min_samples_leaf= 1, min_samples_split= 2)

In [48]:
model.fit(x_train_scaled,y_train)

DecisionTreeClassifier()

In [49]:
x_pred=model.predict(x_train_scaled)

In [50]:
from sklearn.metrics import accuracy_score
train_acc = accuracy_score(x_pred,y_train)
print("training accuracy is ",train_acc)

training accuracy is  1.0

In [51]:
y_pred=model.predict(x_test_scaled)

In [52]:
from sklearn.metrics import accuracy_score
test_acc = accuracy_score(y_test,y_pred)
print("testing accuracy is ",test_acc)

testing accuracy is  1.0

In [53]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
param_grid = {'criterion': ['gini', 'entropy'],'max_depth': [None, 3, 5, 10],'min_samples_split': [2, 5, 10],'min_samples_leaf': [1, 2, 4]
}
dt=DecisionTreeClassifier()
# GridSearchCV
grid_search = GridSearchCV(estimator=dt,param_grid=param_grid,cv=5,scoring='accuracy',)
# Train
grid_search.fit(X_train, y_train)
# Best parameters
print("Best Parameters:", grid_search.best_params_)
print("Best CV Accuracy:", grid_search.best_score_)

Best Parameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best CV Accuracy: 1.0

In [54]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(max_depth= 7, min_samples_leaf= 4, min_samples_split= 16, n_estimators= 156)

In [55]:
model.fit(x_train_scaled,y_train)

RandomForestClassifier(max_depth=7, min_samples_leaf=4, min_samples_split=16,
                       n_estimators=156)

In [56]:
x_pred=model.predict(x_train_scaled)

In [57]:
from sklearn.metrics import accuracy_score
train_acc = accuracy_score(x_pred,y_train)
print("training accuracy is ",train_acc)

training accuracy is  1.0

In [58]:
y_pred=model.predict(x_test_scaled)

In [59]:
from sklearn.metrics import accuracy_score
test_acc = accuracy_score(y_test,y_pred)
print("testing accuracy is ",test_acc)

testing accuracy is  1.0

In [60]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
# PARAMETERS
param_dist = {
    'n_estimators': randint(50, 300),
    'max_depth': randint(1, 20),
    'min_samples_split': randint(2, 20),
    'min_samples_leaf': randint(1, 10)
}
# RANDOM SEARCH
random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)
# FIT
random_search.fit(x_train, y_train)
# OUTPUT
print("Best Parameters:", random_search.best_params_)
print("Best Score:", random_search.best_score_)

Best Parameters: {'max_depth': 7, 'min_samples_leaf': 4, 'min_samples_split': 16, 'n_estimators': 156}
Best Score: 1.0